# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Naia Iturrioz Studio"
description: "Naia Iturrioz Studio"
author:      "Naia Iturrioz"
